### PR TITLE
Change LiDAR and Camera visualization default to ON

### PR DESCRIPTION
**Pull request by t-kitajima**
Changes to the following items in the Turtlebot3 e-manual
http://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#standalone-gazebo-plugin

The initial value is modified so that LiDAR and Camera are visualized at startup.

### CODE REVIEW

**Comment by routiful** [comment]
@t-kitajima 

Is there any reason that values you changed are initially ON?

**Comment by t-kitajima** [comment]
@routiful 
The reason is that it is not visualized when executed according to the e-manual procedure.
I expects LiDAR and CAMERA to be visualized when executed.
What do you think about this?

**Comment by routiful** [comment]
@t-kitajima 
I agree your opinion. However, in my opinion, visualization of sensor data is not essential in Gazebo simulator. To visualize it makes higher computation and complex monitoring.
I suggest that we would add some information how to enable or disable it in emanual.

**Comment by t-kitajima** [comment]
@routiful 
all right.
Withdraw this PR and add it to the electronic manual.

**Comment by routiful** [comment]
@t-kitajima Great. Thanks :)

**Pull request closed without merging**
